language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - libstdc++-5-dev
            - clang-3.8
      env: COMPILER=clang++-3.8

# command to run tests
script: 
  - cd tests
  - export CXX=$COMPILER
  - cmake ./
  - make -j 2
  - ./ftl_tests
  - cd should_fail
  - ctest

